#################################
# RISCV Toolchain
#################################

TARGET = riscv64-unknown-elf

GCC = $(TARGET)-gcc
CXX = $(TARGET)-g++
CP = $(TARGET)-objcopy
OBJDUMP = $(TARGET)-objdump
DG = $(TARGET)-gdb
SIZE = $(TARGET)-size


#################################
# Flags
#################################

# SoC Settings
ARCH = rv64imafdc
ABI = lp64d
ARCHFLAGS = -march=$(ARCH) -mabi=$(ABI)

CFLAGS = -std=gnu99 -O3 -fno-common -fno-builtin-printf -Wall
CFLAGS += $(ARCHFLAGS)
# LDFLAGS = -static

# include libgloss.mk

PROGRAMS = ntt128 ntt8bigint

.DEFAULT_GOAL := default


#################################
# Build
#################################

spiflash.img: spiflash.py
	python3 $<

%.o: %.S
	$(GCC) $(CFLAGS) -D__ASSEMBLY__=1 -c $< -o $@

#%.o: %.c #mmio.h spiflash.h
#	$(GCC) $(CFLAGS) -c $< -o $@

%.riscv: %.c
	$(GCC) $(CFLAGS) -c $< -o $@

#%.riscv: %.o #$(libgloss)
#	$(GCC) $(LDFLAGS) $< -o $@

%.dump: %.riscv
	$(OBJDUMP) --disassemble=ntt8bigint $< > $@

%.s: %.c
	$(GCC) $(CFLAGS) -S -c $< -o $@

%.csv: %.s
	./analysis.py $<

#################################
# Recipes
#################################

.PHONY: clean
clean:
	rm -f *.riscv *.o *.dump *.s *.csv
	$(if $(libgloss),rm -rf $(libgloss_builddir)/)

.PHONY: default
default: $(addsuffix .riscv, $(PROGRAMS)) #spiflash.img

.PHONY: dumps
dumps: $(addsuffix .dump, $(PROGRAMS))

.PHONY: assemble
assemble: $(addsuffix .s, $(PROGRAMS))

.PHONY: analyze
analyze: $(addsuffix .csv, $(PROGRAMS))
